version: '3.7'
services:
    app:
        image: php:7.2-fpm-alpine
        container_name: symfony-app
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            - .:/app:cached
            - ./var/cache:/app/var/cache:rw,delegated
            - ./var/log/app:/app/var/log:rw,delegated
            - ./var/log/debug:/var/log/xdebug:rw,delegated
    web:
        image: nginx:1.15-alpine
        container_name: symfony-web
        depends_on:
            - app
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./public:/app/public:ro,cached
            - ./var/log/web:/var/log/nginx:rw,delegated
