version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
            target: dev
        image: symfony-app:dev
        container_name: symfony-app
        depends_on:
            - db
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - APP_ENV=${APP_ENV}
        volumes:
            - .:/app:cached
            - ./var/cache:/app/var/cache:rw,delegated
            - ./var/log/app:/app/var/log:rw,delegated
            - ./var/log/debug:/var/log/xdebug:rw,delegated
            - ./var/report/phpunit:/var/report/phpunit:rw,delegated
    db:
        image: mariadb:10.4
        container_name: symfony-db
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - symfony-db-data:/var/lib/mysql:rw
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        image: symfony-web:dev
        container_name: symfony-web
        depends_on:
            - app
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./public:/app/public:ro,cached
            - ./var/log/web:/var/log/nginx:rw,delegated
volumes:
    symfony-db-data: {}
